export const GET_MAINPAGEMOVIES='GET_MAINPAGEMOVIES';
export const SET_LOCATION='SET_LOCATION';
export const GET_FIRSTPAGEADVANDNEWS='GET_FIRSTPAGEADVANDNEWS';
export const GET_ISHOTMOVIES='GET_ISHOTMOVIES';
export const GET_ISCOMINGMOVIES='GET_ISCOMINGMOVIES';
export const GET_MOVIEDETAIL='GET_MOVIEDETAIL';