const footNavData=[
    {
        title:'首页',
        img:require('../assets/top-nav/home.png'),
        active:true,
        foreColor:"blue",
        router:'home'
    },
    {
        title:'购票',
        img:require('../assets/top-nav/ticket.png'),
        active:false,
        foreColor:"blue",
        router:'ticket'
    },
    {
        title:'商城',
        img:require('../assets/top-nav/mall.png'),
        active:false,
        foreColor:"blue",
        router:'movie'
    },
    {
        title:'发现',
        img:require('../assets/top-nav/seen.png'),
        active:false,
        foreColor:"blue",
        router:'yugaopian'
    },
    {
        title:'我的',
        img:require('../assets/top-nav/my.png'),
        active:false,
        foreColor:"blue",
        router:'comments'
    }
];

export default footNavData;